name: RH
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::fastapi
  - conda-forge::uvicorn
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - requests
  - python-dotenv
  - pip
  - pip:
    - requests
    - python-dotenv
